image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
  - ps: >-
      $env:Path = "D:\User\lprabhakaran\AppData\Local\Programs\Git\cmd;$env:Path"
      $env:Path = "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin;$env:Path"
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: Install-Product node $env:nodejs_version
  - dotnet restore
  - dotnet --version
  - dotnet restore AspNetCoreProtobufFormatters.sln
  - dotnet restore SystemTests.sln
  - choco install googlechrome
build_script:
- dotnet build AspNetCoreProtobufFormatters.sln
- dotnet build SystemTests.sln
before_build:
- appveyor-retry dotnet restore AspNetCoreProtobufFormatters.sln -v Minimal
